### ISSUE TITLE
NoAvailablePixelFormat

### ISSUE THREAD

**Issue by bestouff** [trsoluti/space_shooter#5]
Debian/testing:

```rust
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoAvailablePixelFormat', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/macros.rs:18
   9: core::result::Result<T,E>::unwrap
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/result.rs:798
  10: gfx_window_glutin::init_raw
             at /home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_window_glutin-0.27.0/src/lib.rs:144
  11: gfx_window_glutin::init
             at /home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_window_glutin-0.27.0/src/lib.rs:67
  12: amethyst_renderer::renderer::init_backend
             at /home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst_renderer-0.10.4/src/renderer.rs:308
  13: amethyst_renderer::renderer::RendererBuilder::build
             at /home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst_renderer-0.10.4/src/renderer.rs:212
  14: amethyst_renderer::system::RenderSystem<P>::build
             at /home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst_renderer-0.10.4/src/system.rs:63
  15: <amethyst_renderer::bundle::RenderBundle<B,P> as amethyst_core::bundle::SystemBundle>::build
             at /home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst_renderer-0.10.4/src/bundle.rs:120
  16: amethyst::game_data::GameDataBuilder::with_bundle
             at /home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.10.0/src/game_data.rs:222
  17: space_shooter::run
             at src/main.rs:153
  18: space_shooter::main
             at src/main.rs:180
  19: std::rt::lang_start::{{closure}}
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/rt.rs:64
  20: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  21: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  22: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  23: std::rt::lang_start
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/rt.rs:64
  24: main
  25: __libc_start_main
  26: _start
```

**Comment by trsoluti** [comment]
It appears, based on [here](https://github.com/PistonDevelopers/conrod/issues/1094), that your system doesn't support SRGB pixel format.

Do the examples from Amethyst run? (Use the 0.10 version, not the latest in Github, as the backend has changed completely).

Hope this is helpful.

**Comment by bestouff** [comment]
The ones I tried all fail with
```
thread 'main' panicked at 'assertion failed: desc.min <= desc.max && desc.max < info.levels', /home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.15.5/src/tex.rs:989:5
```

**Comment by bestouff** [comment]
Ok, building an example with `amethyst_tools` fails the same. Closing.  
Thanks for the help

**Comment by bestouff** [comment]
FWIW just replacing `multisampling` `1` with `0` in `resources/display_config.ron` fixes the issue.
